import math
x1 = 3
y1 = 4
x2 = 7
y2 = 1
TOTAL = 0
TOTALX=0
TOTALY=0
TOTALX=(x2 - x1 )
TOTALX= TOTALX*TOTALX
TOTALY=(y2 - y1 )
TOTALY= TOTALY*TOTALY
TOTAL=TOTALX+TOTALY
print ("LA DISTANCIA ENTRE PUNTOS ES " ,TOTAL, "u2")
